# coding: utf-8

"""
    Everestek Custom APIs

    Everestek customs APIs developed as micro-service extension.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from com.everestek.accelerator.evhub.api.management_api import router as ManagementApiRouter


from com.everestek.accelerator.evhub.api.books_api import router as BooksApiRouter

app = FastAPI(
    title="Everestek Custom APIs",
    description="Everestek customs APIs developed as micro-service extension.",
    version="1.0",
    root_path="/evhub/v1",
)

app.include_router(ManagementApiRouter)
app.include_router(BooksApiRouter)
